const ListWords: { [key: string]: string } = {
    "dense": "denso/a",
    "fog": "névoa",
    "covered": "cobriu",
    "forest": "floresta",
    "making": "tornando",
    "it": "isso",
    "difficult": "difícil",
    "to": "para",
    "see": "enxergar",
    "a": "um/uma",
    "few": "poucos",
    "meters": "metros",
    "away": "de distância",
    "adventurers": "aventureiros",
    "guided": "guiados",
    "by": "por",
    "an": "uma",
    "old": "antiga",
    "compass": "bússola",
    "proceeded": "avançavam",
    "with": "com",
    "caution": "cautela",
    "sound": "som",
    "of": "de",
    "crushed": "esmagadas",
    "leaves": "folhas",
    "underfoot": "sob os pés",
    "was": "era",
    "only": "única",
    "thing": "coisa",
    "that": "aquilo/que",
    "broke": "quebrava",
    "eerie": "assustador",
    "silence": "silêncio",
    "they": "estavam",
    "were": "estavam",
    "in": "em",
    "search": "busca",
    "legendary": "lendário",
    "artifact": "artefato",
    "which": "quais",
    "according": "segundo",
    "legend": "lenda",
    "had": "tinha",
    "power": "poder",
    "control": "controlar",
    "time": "tempo",
    "every": "passo",
    "feeling": "sensação",
    "being": "de serem",
    "watched": "observados",
    "intensified": "intensificava",
    "air": "ar",
    "heavy": "carregado",
    "humidity": "umidade",
    "and": "e",
    "chilling": "frio",
    "cold": "gelado",
    "made": "fazia",
    "their": "deles",
    "faces": "rostos",
    "contract": "se contraíssem",
    "surrounding": "vegetação",
    "vegetation": "ao redor",
    "seemed": "parecia",
    "twist": "torcer",
    "intertwine": "se entrelaçar",
    "creating": "criando",
    "natural": "natural",
    "labyrinth": "labirinto",
    "challenged": "desafiava",
    "perception": "percepção",
    "rays": "raios",
    "light": "luz",
    "the":"o/a",
    "managed": "conseguiram",
    "penetrate": "penetrar",
    "cast": "projetavam",
    "distorted": "distorcidas",
    "shadows": "sombras",
    "heightening": "aumentando",
    "sense": "sensação",
    "something": "algo",
    "about": "prestes a",
    "happen": "acontecer",
    "swaying": "balançando",
    "gently": "suavemente",
    "pointed": "indicava",
    "direction": "direção",
    "increasingly": "cada vez mais",
    "erratic": "errática",
    "group": "grupo",
    "approached": "se aproximava",
    "clearing": "clareira",
    "where": "onde",
    "ancient": "antigos",
    "texts": "textos",
    "might": "talvez",
    "be": "estar",
    "hidden": "escondido",
    "hopes": "esperanças",
    "fears": "medos",
    "mingled": "se misturavam",
    "as": "enquanto",
    "continued": "continuavam",
    "journey": "jornada"
  };
  
  export default ListWords;
  