const ListWords: { [key: string]: string } = {
"a": "um/uma",
  "adventurers": "aventureiros",
  "an": "uma",
  "away": "de distância",
  "by": "por",
  "compass": "bússola",
  "caution": "cautela",
  "covered": "cobriu",
  "crushed": "esmagadas",
  "dense": "denso/a",
  "difficult": "difícil",
  "few": "poucos",
  "fog": "névoa",
  "forest": "floresta",
  "guided": "guiados",
  "it": "isso",
  "leaves": "folhas",
  "making": "tornando",
  "meters": "metros",
  "old": "antiga",
  "of": "de",
  "proceeded": "avançavam",
  "see": "enxergar",
  "sound": "som",
  "underfoot": "sob os pés",
  "was": "era",
  "with": "com",
  "according": "segundo",
  "air": "ar",
  "artifact": "artefato",
  "being": "de serem",
  "broke": "quebrava",
  "chilling": "frio",
  "cold": "gelado",
  "control": "controlar",
  "creating": "criando",
  "every": "passo",
  "eerie": "assustador",
  "feeling": "sensação",
  "faces": "rostos",
  "had": "tinha",
  "heavy": "carregado",
  "humidity": "umidade",
  "in": "em",
  "intensified": "intensificava",
  "intertwine": "se entrelaçar",
  "labyrinth": "labirinto",
  "legend": "lenda",
  "legendary": "lendário",
  "light": "luz",
  "made": "fazia",
  "natural": "natural",
  "power": "poder",
  "perception": "percepção",
  "rays": "raios",
  "search": "busca",
  "seemed": "parecia",
  "silence": "silêncio",
  "surrounding": "vegetação",
  "thing": "coisa",
  "that": "aquilo/que",
  "time": "tempo",
  "to": "para",
  "twist": "torcer",
  "vegetation": "ao redor",
  "watched": "observados",
  "were": "estavam",
  "which": "quais",
  "only": "única",
  "their": "deles",
  "challenged": "desafiava",
  "contract": "se contraíssem",


  "about": "prestes a",
  "ancient": "antigos",
  "approached": "se aproximava",
  "as": "enquanto",
  "be": "estar",
  "best": "melhor",
  "campfire": "fogueira",
  "cast": "projetavam",
  "clearing": "clareira",
  "continues": "continuavam",
  "creatures": "criaturas",
  "discussed": "discutiam",
  "direction": "direção",
  "distorted": "distorcidas",
  "erratic": "errática",
  "encounters": "encontros",
  "fears": "medos",
  "gently": "suavemente",
  "group": "grupo",
  "hidden": "escondido",
  "hopes": "esperanças",
  "heightening": "aumentando",
  "increasingly": "cada vez mais",
  "journey": "jornada",
  "magical": "mágicos",
  "managed": "conseguiram",
  "might": "talvez",
  "mingled": "se misturavam",
  "penetrate": "penetrar",
  "past": "passado",
  "pointed": "indicava",
  "sense": "sensação",
  "shadows": "sombras",
  "something": "algo",
  "stories": "histórias",
  "swaying": "balançando",
  "told": "contavam",
  "texts": "textos",
  "where": "onde",


  "account": "relato",
  "alert": "alertas",
  "amidst": "em meio a",
  "attack": "ataque",
  "biting": "cortante",
  "come": "por vir",
  "contrasting": "contrastando",
  "decipher": "decifrar",
  "dangers": "perigos",
  "difficulties": "dificuldades",
  "distant": "distante",
  "discussion": "discussão",
  "dragons": "dragões",
  "each": "cada",
  "elves": "elfos",
  "encounter": "encontrar",
  "experienced": "experiente",
  "excited": "animação",
  "explained": "explicava",
  "flames": "chamas",
  "fire": "fogo",
  "glow": "brilho",
  "howl": "uivo",
  "kept": "mantinha",
  "leader": "líder",
  "map": "mapa",
  "marking": "marcando",
  "more": "mais",
  "morning": "manhã",
  "mysterious": "misterioso",
  "night": "noite",
  "nocturnal": "noturnos",
  "prepared": "preparados",
  "progressed": "avançava",
  "proceed": "prosseguir",
  "regain": "restabelecer",
  "reminder": "lembrete",
  "route": "rota",
  "sorcery": "feitiçaria",
  "sounds": "sons",
  "strategy": "estratégia",
  "strength": "força",
  "suddenly": "de repente",
  "sought": "buscado/procurado",
  "symbols": "símbolos",
  "studying": "estudando",
  "tired": "cansado",
  "thicken": "aumentar",
  "threatening": "ameaçador",
  "tried": "tentava",
  "way": "caminho",
  "warm": "quente",
  "warmth": "calor",
  "warrior": "guerreiro",
  "what": "o que",
  "echoed": "ecoou",


  "ahead": "à frente",
  "alive": "ganhar vida",
  "appeared": "apareceu",
  "beyond": "além de",
  "blew": "soprou",
  "briefly": "brevemente",
  "camp": "acampamento",
  "casting": "lançando",
  "carrying": "carregado",
  "challenge": "desafio",
  "causing": "fazendo",
  "courage": "coragem",
  "decision": "decisão",
  "defensive": "defesa",
  "difference": "diferença",
  "danced": "dançava",
  "everyone": "todos",
  "failure": "fracasso",
  "face": "enfrentar",
  "forming": "formando",
  "full": "cheia",
  "gather": "agrupar",
  "ghostly": "fantasmagóricas",
  "hand":"maos",
  "hearts": "corações",
  "heightened": "aguçados",
  "heart": "coração",
  "illuminated": "iluminava",
  "known": "conhecido",
  "knew": "sabiam",
  "moon": "lua",
  "nature": "natureza",
  "path": "caminho",
  "prepare": "preparar",
  "ready": "preparados",
  "reacting": "reagindo",
  "race": "disparar",
  "racing": "acelerado",
  "resonate": "ressoar",
  "scent": "aroma",
  "shroud": "manto",
  "silhouettes": "silhuetas",
  "silver": "prateada",
  "stood": "levantaram",
  "survival": "sobrevivência",
  "tension": "tensão",
  "through": "através",
  "trees": "árvores",
  "unfamiliar": "desconhecido",
  "weapons": "armas",
  "wind": "vento",
  "quest": "busca",
  "the": "o/a",

};

export default ListWords;
